/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 80046 (8.0.46)
 Source Host           : localhost:3306
 Source Schema         : stock

 Target Server Type    : MySQL
 Target Server Version : 80046 (8.0.46)
 File Encoding         : 65001

 Date: 27/04/2026 16:19:11
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for stock_daily_full
-- ----------------------------
DROP TABLE IF EXISTS `stock_daily_full`;
CREATE TABLE `stock_daily_full`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `trade_date` date NOT NULL,
  `日期` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `代码` bigint NULL DEFAULT NULL,
  `名称` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `涨幅%` float NULL DEFAULT NULL,
  `现价` float NULL DEFAULT NULL,
  `涨跌` float NULL DEFAULT NULL,
  `买价` float NULL DEFAULT NULL,
  `卖价` float NULL DEFAULT NULL,
  `总量` bigint NULL DEFAULT NULL,
  `现量` bigint NULL DEFAULT NULL,
  `涨速%` float NULL DEFAULT NULL,
  `换手%` float NULL DEFAULT NULL,
  `今开` float NULL DEFAULT NULL,
  `最高` float NULL DEFAULT NULL,
  `最低` float NULL DEFAULT NULL,
  `昨收` float NULL DEFAULT NULL,
  `市盈(动)` float NULL DEFAULT NULL,
  `总金额` float NULL DEFAULT NULL,
  `量比` float NULL DEFAULT NULL,
  `细分行业` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `地区` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `振幅%` float NULL DEFAULT NULL,
  `均价` float NULL DEFAULT NULL,
  `内盘` bigint NULL DEFAULT NULL,
  `外盘` bigint NULL DEFAULT NULL,
  `内外比` float NULL DEFAULT NULL,
  `买量` bigint NULL DEFAULT NULL,
  `卖量` bigint NULL DEFAULT NULL,
  `未匹配量` bigint NULL DEFAULT NULL,
  `开盘金额` float NULL DEFAULT NULL,
  `开盘换手Z` float NULL DEFAULT NULL,
  `封成比` float NULL DEFAULT NULL,
  `封单额` float NULL DEFAULT NULL,
  `流通股(亿)` float NULL DEFAULT NULL,
  `流通市值` bigint NULL DEFAULT NULL,
  `AB股总市值` decimal(20, 4) NULL DEFAULT NULL,
  `强弱度%` float NULL DEFAULT NULL,
  `活跃度` bigint NULL DEFAULT NULL,
  `笔均量` bigint NULL DEFAULT NULL,
  `笔换手%` float NULL DEFAULT NULL,
  `连涨天` bigint NULL DEFAULT NULL,
  `昨涨幅%` float NULL DEFAULT NULL,
  `3日涨幅%` float NULL DEFAULT NULL,
  `20日涨幅%` float NULL DEFAULT NULL,
  `60日涨幅%` float NULL DEFAULT NULL,
  `年初至今%` float NULL DEFAULT NULL,
  `年涨停天` bigint NULL DEFAULT NULL,
  `换手Z` float NULL DEFAULT NULL,
  `流通市值Z` decimal(20, 4) NULL DEFAULT NULL,
  `市盈(TTM)` float NULL DEFAULT NULL,
  `市盈(静)` float NULL DEFAULT NULL,
  `贝塔系数` float NULL DEFAULT NULL,
  `近日指标提示` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `短期形态` float NULL DEFAULT NULL,
  `中期形态` float NULL DEFAULT NULL,
  `长期形态` float NULL DEFAULT NULL,
  `开盘%` float NULL DEFAULT NULL,
  `最高%` float NULL DEFAULT NULL,
  `最低%` float NULL DEFAULT NULL,
  `均涨幅%` float NULL DEFAULT NULL,
  `实体涨幅%` float NULL DEFAULT NULL,
  `回头波%` float NULL DEFAULT NULL,
  `攻击波%` float NULL DEFAULT NULL,
  `财务更新` bigint NULL DEFAULT NULL,
  `上市日期` bigint NULL DEFAULT NULL,
  `总股本(亿)` float NULL DEFAULT NULL,
  `B/A股(亿)` float NULL DEFAULT NULL,
  `H股(亿)` float NULL DEFAULT NULL,
  `总资产(亿)` float NULL DEFAULT NULL,
  `净资产(亿)` float NULL DEFAULT NULL,
  `少数股权(亿)` float NULL DEFAULT NULL,
  `资产负债率%` float NULL DEFAULT NULL,
  `流动资产(亿)` float NULL DEFAULT NULL,
  `固定资产(亿)` float NULL DEFAULT NULL,
  `无形资产(亿)` float NULL DEFAULT NULL,
  `流动负债(亿)` float NULL DEFAULT NULL,
  `货币资金(亿)` float NULL DEFAULT NULL,
  `存货(亿)` float NULL DEFAULT NULL,
  `应收账款(亿)` float NULL DEFAULT NULL,
  `合同负债(亿)` float NULL DEFAULT NULL,
  `资本公积金(亿)` float NULL DEFAULT NULL,
  `营业收入(亿)` float NULL DEFAULT NULL,
  `营业成本(亿)` float NULL DEFAULT NULL,
  `营业利润(亿)` float NULL DEFAULT NULL,
  `投资收益(亿)` float NULL DEFAULT NULL,
  `利润总额(亿)` float NULL DEFAULT NULL,
  `税后利润(亿)` float NULL DEFAULT NULL,
  `净利润(亿)` float NULL DEFAULT NULL,
  `扣非净利润(亿)` float NULL DEFAULT NULL,
  `未分利润(亿)` float NULL DEFAULT NULL,
  `经营现金流(亿)` float NULL DEFAULT NULL,
  `总现金流(亿)` float NULL DEFAULT NULL,
  `股东人数` bigint NULL DEFAULT NULL,
  `人均持股` bigint NULL DEFAULT NULL,
  `人均市值` varchar(17) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `利润同比%` float NULL DEFAULT NULL,
  `收入同比%` float NULL DEFAULT NULL,
  `市净率` float NULL DEFAULT NULL,
  `市现率` float NULL DEFAULT NULL,
  `市销率` float NULL DEFAULT NULL,
  `股息率%` float NULL DEFAULT NULL,
  `每股收益` varchar(17) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `每股净资` float NULL DEFAULT NULL,
  `每股公积` float NULL DEFAULT NULL,
  `每股未分配` float NULL DEFAULT NULL,
  `每股现金流` float NULL DEFAULT NULL,
  `权益比%` float NULL DEFAULT NULL,
  `净益率%` varchar(19) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `毛利率%` float NULL DEFAULT NULL,
  `营业利润率%` float NULL DEFAULT NULL,
  `净利润率%` float NULL DEFAULT NULL,
  `研发费用(亿)` float NULL DEFAULT NULL,
  `员工人数` bigint NULL DEFAULT NULL,
  `交易代码` bigint NULL DEFAULT NULL,
  `自选日` bigint NULL DEFAULT NULL,
  `自选价` float NULL DEFAULT NULL,
  `自选收益%` float NULL DEFAULT NULL,
  `连板天` int NULL DEFAULT NULL,
  `几天几板` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `col_5日涨幅%` decimal(20, 4) NULL DEFAULT NULL,
  `col_10日涨幅%` decimal(20, 4) NULL DEFAULT NULL,
  `开盘抢筹%` decimal(20, 4) NULL DEFAULT NULL,
  `开盘昨比%` decimal(20, 4) NULL DEFAULT NULL,
  `3日成交额` decimal(20, 4) NULL DEFAULT NULL,
  `3日换手Z` decimal(20, 4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_stock_date`(`代码` ASC, `trade_date` ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4575911 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

SET FOREIGN_KEY_CHECKS = 1;
